# Generated by Django 4.1.3 on 2022-12-21 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aulasfcm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Edificios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(max_length=100)),
            ],
        ),
    ]
