# Generated by Django 4.1.3 on 2023-02-02 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aulasfcm', '0005_alter_aulas_edificio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=254)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=100)),
            ],
        ),
    ]
