# Generated by Django 4.1.3 on 2023-02-03 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aulasfcm', '0006_entidades'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entidades',
            name='telefono',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
