# Generated by Django 4.1.3 on 2023-02-08 23:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aulasfcm', '0007_alter_entidades_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='edificios',
            name='gestores',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='entidades',
            name='telefono',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
