# Generated by Django 4.1.3 on 2023-03-08 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aulasfcm', '0008_edificios_gestores_alter_entidades_telefono'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
            ],
        ),
    ]
