# Generated by Django 4.1.3 on 2023-03-13 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aulasfcm', '0009_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='aula',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='aulasfcm.aulas'),
            preserve_default=False,
        ),
    ]
