# Generated by Django 4.1.3 on 2023-03-27 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aulasfcm', '0010_event_aula'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='entidad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='aulasfcm.entidades'),
            preserve_default=False,
        ),
    ]
