# Generated by Django 4.1.3 on 2023-04-22 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aulasfcm', '0012_event_siguiente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='title',
        ),
    ]
